---
title: "exer"
author: "yoon"
format: pdf
editor: visual
---

# 기말 연습용

## 1. 선형을 활용한 예측

### 1-1. loading

```{r}
library(caret)
library(MASS)
library(tidyverse)
```

```{r}
gpa <- read.csv("dataforclass/gpa1.csv",header = TRUE,
                sep = "\t")
str(gpa)
```

### 1-2. train과 test 데이터 구분

-   데이터 구분

```{r}
train_i <- createDataPartition(gpa$colGPA,
                               p = 0.8,
                               list = FALSE) 
train <- gpa[train_i,]
test <- gpa[-train_i,]
str(train)
str(test)
```

### 1-3. 선형모형 제작과 예측 실험

-   선형 모델 제작

```{r}
lm_gpa <- lm(colGPA~., data = train)
summary(lm_gpa)
```

-   예측값 계산

```{r}
predic_gpa <- predict(lm_gpa,newdata = test)

result <- data.frame(
  actual = test$colGPA,
  predict = predic_gpa
)
head(result)
```

-   예측값 시각화

```{r}
result |> 
  ggplot(mapping = aes(x = actual, y = predict)) + 
  geom_point() + 
  geom_abline(intercept = 0 , slope = 1, color = "red", linetype = "dashed")
  labs( 
    x = "실제 GPA", y = "예측 GPA"
    )
```

-   MSE 와 RMSE

```{r}
# 계산
mse = mean(result$actual - result$predict)^2
rmse = sqrt(mse)

# 값 확인 
print(paste("MSE = ", mse))
print(paste("RMSE = ", rmse))
```

### 1-4. 모델 선택

-   AIC 방법을 활용한 모델 선택

```{r}
# 모델 확인 
slected_model <-  stepAIC(lm(colGPA ~.,data = train),
                          direction = "both",
                          trace = FALSE
                          )

# 선택된 모델 확인
model <- names(coef(slected_model))[-1]
print(model)

# 모델 붙여넣기 
temp <- paste(model, collapse = " + ")
formula <-as.formula(paste("colGPA ~",temp))

lm_selected <- lm(formula, data = train)
summary(lm_selected)
```

## 2. Q3

```{r}
install.packages("AER")
# AER 패키지 로드
library(AER)

# CPS1988 데이터셋 불러오기
data("CPS1988")

# 데이터셋의 첫 몇 행 확인
head(CPS1988)
```

### A. 교육수익률을 추정

```{r}
View(CPS1988)
str(CPS1988)

# 교육 수익률 추정.
# 로그-로그 회귀 모델 적용
model <- lm(log(wage) ~ log(education), data = CPS1988)

# 모델 요약 출력
summary(model)

# 교육의 1% 증가에 따른 임금의 백분율 변화 계산
coef <- coef(model)["log(education)"]
percent_change <- (exp(coef) - 1) * 100

# 결과 출력
cat("교육의 1% 증가에 따른 임금의 백분율 변화:", round(percent_change, 2), "%\n")
```